# Generated by Django 5.2.3 on 2025-07-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='discoveries.rating'),
        ),
    ]
