# Generated by Django 5.2.3 on 2025-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0004_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='brief',
            field=models.CharField(blank=True, help_text='Optional summary for cards.', max_length=300),
        ),
        migrations.AddField(
            model_name='country',
            name='brief',
            field=models.CharField(blank=True, help_text='Optional summary for cards.', max_length=300),
        ),
        migrations.AddField(
            model_name='landmark',
            name='brief',
            field=models.CharField(blank=True, help_text='Optional summary for cards.', max_length=300),
        ),
    ]
